import {useEffect,useState} from 'react';
import {Routes,Route,Navigate,useLocation} from 'react-router-dom';
import {get,clearAuth} from './lib/api';
import {User} from './types';
import AppShell from './layout/AppShell';
import Login from './pages/Login'; import Register from './pages/Register'; import Dashboard from './pages/Dashboard';
import Team from './pages/Team'; import Departments from './pages/Departments'; import Projects from './pages/Projects'; import Partners from './pages/Partners';
import TargetLists from './pages/TargetLists'; import Speakers from './pages/Speakers'; import Tasks from './pages/Tasks'; import Goals from './pages/Goals'; import Mkt from './pages/Mkt'; import Activity from './pages/Activity'; import Imports from './pages/Imports'; import Search from './pages/Search'; import Admin from './pages/Admin'; import ProjectDashboard from './pages/ProjectDashboard';
function Protected({user,children}:{user:User|null;children:any}){return user?<AppShell user={user}>{children}</AppShell>:<Navigate to="/login" replace/>}
export default function App(){const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(true);const loc=useLocation();useEffect(()=>{if(loc.pathname==='/login'||loc.pathname==='/register'){setLoading(false);return} get<User>('/users/me').then(setUser).catch(()=>clearAuth()).finally(()=>setLoading(false))},[loc.pathname]); if(loading)return <div className="loadingpage">Loading SHIFT…</div>;return <Routes><Route path="/login" element={<Login onLogin={()=>get<User>('/users/me').then(setUser)}/>}/><Route path="/register" element={<Register onLogin={()=>get<User>('/users/me').then(setUser)}/>}/><Route path="/" element={<Protected user={user}><Dashboard user={user}/></Protected>}/><Route path="/team" element={<Protected user={user}><Team user={user}/></Protected>}/><Route path="/departments" element={<Protected user={user}><Departments user={user}/></Protected>}/><Route path="/project-dashboard" element={<Protected user={user}><ProjectDashboard/></Protected>}/><Route path="/projects" element={<Protected user={user}><Projects user={user}/></Protected>}/><Route path="/partners" element={<Protected user={user}><Partners user={user}/></Protected>}/><Route path="/target-lists" element={<Protected user={user}><TargetLists user={user}/></Protected>}/><Route path="/speakers" element={<Protected user={user}><Speakers user={user}/></Protected>}/><Route path="/tasks" element={<Protected user={user}><Tasks user={user}/></Protected>}/><Route path="/goals" element={<Protected user={user}><Goals user={user}/></Protected>}/><Route path="/mkt" element={<Protected user={user}><Mkt/></Protected>}/><Route path="/activity" element={<Protected user={user}><Activity/></Protected>}/><Route path="/imports" element={<Protected user={user}><Imports/></Protected>}/><Route path="/search" element={<Protected user={user}><Search/></Protected>}/><Route path="/admin" element={<Protected user={user}>{user?.role==='ADMIN'?<Admin/>:<Navigate to="/" replace/>}</Protected>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
